In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [3]:
#Training the data using logistic and measuring the score. 
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.95

In [4]:
#Trying for the SVM too.
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)   #Which performs poorly.

0.387037037037037

In [5]:
#trying for Random forest.
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9574074074074074

In [6]:
#Above,we ere measurnig the performance of these three models.
#BAUT USING THE TRAIN,TEST SPLIT. The results keep on changing as you run the train and test split line

In [7]:
#Using the K FOLD cross validation to demontrate that changing process above.

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf  #using 3 splits

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

    #the iterator [1,2,3,4,5,6,7,8,9],which returns the train and test index for each of the iteration.
    #it has divided the iterator into 3 folds.first 3 for testing and the 6 for training.
    #In the second, the previous test gets into the training set.And repeats the procedure like that.

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
#Use KFold for our digits example
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [11]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [12]:
scores_logistic


[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [13]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [14]:
scores_rf

[0.9348914858096828, 0.9616026711185309, 0.9215358931552587]

In [15]:
#Using the cross_val_score function to demonstrate what the code has been doing.
from sklearn.model_selection import cross_val_score

In [16]:
#Logistic regression model performance using cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)
#So, it does the same thing as in the loop above.

array([0.89482471, 0.95325543, 0.90984975])

In [17]:
# svm model performance using cross_val_score
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [18]:
# random forest performance using cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.91819699, 0.94323873, 0.92320534])

In [19]:
#Comparing these classifiers with different parameters--Parameter tuning e.g running the random classifier with different trees or estimators
#Parameter tunning using k fold cross validation


In [20]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8759310986964618

In [21]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9365673494723774